### ISSUE TITLE
Concerning warning when building

### ISSUE THREAD

**Issue by JBorrow** [ICRAR/VELOCIraptor-STF#58]
**Describe the bug**
I get the following warning when building on my laptop:

```
/Users/mphf18/Documents/swift/VELOCIraptor-STF/src/ui.cxx:811:22: note: use '=='
      to turn this assignment into an equality comparison
                if (j=line.find(sep)){
                     ^
                     ==
```

Using 
```
Apple clang version 11.0.0 (clang-1100.0.33.8)
Target: x86_64-apple-darwin20.2.0
```
```
cmake -DVR_USE_SWIFT_INTERFACE=ON -DVR_USE_HYDRO=OND -DCMAKE_CXX_FLAGS="-fPIC" -DCMAKE_BUILD_TYPE=Release -DOpenMP_CXX_FLAGS="-Xpreprocessor -fopenmp -I/usr/local/opt/libomp/include" -DOpenMP_CXX_LIB_NAMES="omp" -DOpenMP_omp_LIBRARY=/usr/local/opt/libomp/lib/libomp.dylib ..
```

Might be worth checking out.

**Comment by rtobar** [comment]
A fix has been added in the `issue-58` branch, which after quick testing will be merged back to the `master` branch (and then this issue can be closed). Please note that although the warning is true, and has been addressed, the code didn't lend itself to a crash, and had the expected behavior anyway.

**Comment by rtobar** [comment]
Merged to the `master`, warning should be gone now. Thanks @JBorrow for reporting!

**Comment by JBorrow** [comment]
Thanks very much for fixing this so quickly!
